In [1]:
import numpy as np

In [42]:
A = np.array([[3,4],[4,3]])

In [62]:
B = np.transpose(A).dot(A)
B

array([[25, 24],
       [24, 25]])

In [65]:
L, V = np.linalg.eig(B) #Тут специально поменял порядок
L = np.diag(L) #Перевел в диагональную матрицу
print(L)
print(V)

[[49.  0.]
 [ 0.  1.]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [66]:
S = np.sqrt(L)
S

array([[7., 0.],
       [0., 1.]])

In [67]:
U = A.dot(V).dot(np.linalg.matrix_power(S,-1))
U

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [68]:
U.dot(S).dot(np.transpose(V))

array([[3., 4.],
       [4., 3.]])