In [17]:
import pandas as pd
from sklearn.decomposition import TruncatedSVD
import numpy as np
df = pd.read_csv('Iris.csv', sep=',', decimal='.', index_col='Id')

In [18]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [19]:
data = np.matrix(df.iloc[:, :4])
data.shape

(150, 4)

In [20]:
svd = TruncatedSVD(n_components=2)
svd.fit(data)

components = svd.components_.transpose()

reduced_data_svd = np.matmul(data, components)

reduced_data_svd.shape

(150, 2)

In [40]:
U,S,Vt = np.linalg.svd(data, full_matrices = True)

In [45]:
U

matrix([[-6.16171172e-02,  1.29969428e-01, -5.58364155e-05, ...,
         -9.34637342e-02, -9.60224157e-02, -8.09922905e-02],
        [-5.80722977e-02,  1.11371452e-01,  6.84386629e-02, ...,
          3.66755322e-02, -3.24463474e-02,  1.27273399e-02],
        [-5.67633852e-02,  1.18294769e-01,  2.31062793e-03, ...,
          3.08252776e-02,  1.95234663e-01,  1.35567696e-01],
        ...,
        [-9.40702260e-02, -4.98348018e-02, -4.14958083e-02, ...,
          9.81822841e-01, -2.17978813e-02, -8.85972146e-03],
        [-9.48993908e-02, -5.62107520e-02, -2.12386574e-01, ...,
         -2.14264126e-02,  9.42038920e-01, -2.96933496e-02],
        [-8.84882764e-02, -5.16210172e-02, -9.51442925e-02, ...,
         -8.52768485e-03, -3.02139863e-02,  9.73577349e-01]])

In [48]:
S

array([95.95066751, 17.72295328,  3.46929666,  1.87891236])

In [49]:
Vt

matrix([[-0.75116805, -0.37978837, -0.51315094, -0.16787934],
        [ 0.28583096,  0.54488976, -0.70889874, -0.34475845],
        [ 0.49942378, -0.67502499, -0.05471983, -0.54029889],
        [ 0.32345496, -0.32124324, -0.48077482,  0.74902286]])