In [3]:
from numpy.linalg import svd

In [4]:
import numpy as np

In [5]:
A=np.array([
   [3,7],
   [5,2]])

In [6]:
A

array([[3, 7],
       [5, 2]])

In [12]:
u, s, vh = np.linalg.svd(A, full_matrices=True)

In [13]:
u.shape, s.shape, vh.shape

((2, 2), (2,), (2, 2))

In [14]:
u

array([[-0.85065081, -0.52573111],
       [-0.52573111,  0.85065081]])

In [15]:
s

array([8.71337969, 3.32821489])

In [16]:
vh

array([[-0.59455781, -0.80405286],
       [ 0.80405286, -0.59455781]])

In [17]:
s=s*np.eye(s.shape[0])

In [18]:
s

array([[8.71337969, 0.        ],
       [0.        , 3.32821489]])

In [19]:
np.dot(u,s).dot(vh)

array([[3., 7.],
       [5., 2.]])